### ISSUE TITLE
💡idea - raw list

### ISSUE THREAD

**Issue by aviadhahami** [Puliczek/awesome-list-of-secrets-in-environment-variables#3]
Hey,
What about having a list of all the tokens w/o the readme?
this way it can be consumed by tools as a list of strings to look for during recons etc

wdyt?
(can pr this ofcourse)

**Comment by Puliczek** [comment]
I didn't create a new file with raw tokens because I wasn't sure if contributions will add tokens to both files (readme + raw_list) every time.

For manual downloads I did create a small tutorial on how to get the raw list:
https://github.com/Puliczek/awesome-list-of-secrets-in-environment-variables#get-raw-list

However, I see that more people want to consume in the real-time clean raw list. So it is a good point to add it :) Would you like to PR "raw_list"?

**Comment by aviadhahami** [comment]
I thought about the double creation as well, what we can do is:
1/ Create a GH action that will extract the names from the README
2/ push the names to the repo w/ a new commit (or to a different branch? wdyt?)
3/ done, contribs will only need to create once

**Comment by Puliczek** [comment]
@aviadhahami What a clever idea, just added GitHub action to auto-generate raw_list.txt :)

Thanks!

**Comment by aviadhahami** [comment]
np, just offered the idea :)
thx for the repo!
